name: Generate Changelog

on:
  push:
    branches: [ master ]

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Generate and Commit Changelog

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Generate Changelog
      uses: smichard/conventional_changelog@2.0.10
      with:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Set Git User Info
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email 'actions@github.com'

    - name: Commit Changelog
      run: |
        git add CHANGELOG.md
        git commit -m "docs: :robot: changelog file generated" || echo "No changes to commit"
        git push