name: Gradle / Validate wrapper

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ "master" ]
    paths:
      - '**/gradlе-wrapper.jar'

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # v3.5.0