name: SDK / CI

on:
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize]
  merge_group:
    branches: [ "master" ]

jobs:

  avoid_reduncy:
    runs-on: ubuntu-24.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  check-for-cc:
    runs-on: ubuntu-latest
    steps:
      - name: check-for-cc
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v2.0.0

  lint:
    name: Lint
    needs: [check-for-cc]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Java
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
      - name: Run detekt tasks
        run: ./gradlew detekt
      - name: Upload SARIF files
        uses: github/codeql-action/upload-sarif@9e8d0789d4a0fa9ceb6b1738f7e269594bdd67f0 # v3.28.9
        if: ${{ always() }}
        with:
          sarif_file: .

  test:
    name: Test
    needs: [check-for-cc]
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        java: [11, 17]
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Java
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
      - name: Run test task
        run: ./gradlew test
