name: SDK / CI

on:
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize]
  merge_group:
    branches: [ "master" ]

jobs:

  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  commit-lint:
    runs-on: ubuntu-latest
    name: Validate all commits
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Conventional Commits Checker
        uses: netodevel/convetional-commits-checker@v1.0.1
        id: commits-check
        with: # do not change the order of params
          target-branch: ${{ github.event.pull_request.base.ref }}  #required
          current-branch: ${{ github.event.pull_request.head.ref }} #required
          pattern: '(feat|fix|ci|chore|docs|test|style|refactor): .{1,}$' #optional custom validation commit

  lint:
    name: Lint
    needs: [commit-lint]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Java
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
      - name: Run detekt tasks
        run: ./gradlew detekt
      - name: Upload SARIF files
        uses: github/codeql-action/upload-sarif@afb54ba388a7dca6ecae48f608c4ff05ff4cc77a # v3.25.15
        if: ${{ always() }}
        with:
          sarif_file: .

  test:
    name: Test
    needs: [commit-lint]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        java: [11, 17]
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Java
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
      - name: Run test task
        run: ./gradlew test
